export const canvasStyles = {
  background: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      overflow: 'hidden',
      pointerEvents: 'auto',
    },
    image: {
      position: 'absolute',
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      zIndex: 1,
    },
    video: {
      position: 'absolute' as const,
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover' as const,
      zIndex: 1,
      transform: 'scaleX(-1)' as const,
    },
  },
  canvas: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      zIndex: 2,
      pointerEvents: 'auto',
      css: { '-webkit-app-region': 'no-drag' },
    },
  },
  subtitle: {
    container: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
      minWidth: 'fit-content',
      maxWidth: '90%',
      zIndex: 3,
      userSelect: 'none',
      willChange: 'transform',
    },
    text: {
      color: '#ff8ac3',
      fontSize: '1.6rem',
      textAlign: 'center',
      lineHeight: '1.4',
      whiteSpace: 'pre-wrap',
      textShadow: '0 0 8px rgba(255, 105, 180, 0.6), 2px 2px 4px rgba(0, 0, 0, 0.6)',
      paddingInline: '8px',
    },
  },
  wsStatus: {
    container: {
      position: 'absolute',
      top: '20px',
      left: '20px',
      zIndex: 2,
      padding: '8px 16px',
      borderRadius: '20px',
      fontSize: '14px',
      fontWeight: 'medium',
      color: 'white',
      transition: 'all 0.2s',
      cursor: 'pointer',
      userSelect: 'none',
      _hover: {
        opacity: 0.8,
      },
    },
  },
};
